# Generated by Django 5.0.2 on 2024-03-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='check_time',
            new_name='checkin',
        ),
        migrations.AddField(
            model_name='logentry',
            name='checkout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
