# Generated by Django 5.0.2 on 2024-03-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers_app', '0002_rename_check_time_logentry_checkin_logentry_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
